language: node_js
node_js:
- 5.7.0
sudo: required
services:
- docker
script:
- docker-compose -f docker-compose-test.yml build
- docker-compose -f docker-compose-test.yml run test
env:
  global:
  - secure: LUfkaD7/JL8aTAhFU2W+n3tUvUdNATz2lc/P2aH2t7wJ5UWxENHS+WBt9E+TAPk+t8MD4pYQQ6M3ajbjVfLrBqAJBJ6fYCUONnSu2zF5+ppXK4UsfPm6HPASPDFKlvPUhcJXd484zwF3AvASHHLOLYKyBXLsQgzzBF3wiG33OlrqD3QrPG/bvth8Js5xOBvGARwBJkWEiGFEhCayh2zgSJ9zRLJJETx6vkscC4uExSjgckr0xA8EgA0Au3dQgaGYHRyv9XoLWcoEETcI7uqNbEYmHBEnU3F4cgqaHIM09OqBl0CCe7WWQySZRstXttOZaNj/cFnlZ7R3z8pIUxVhuanjiVfUlcVXoy+NaG2Koj01E7fYP4/w4AFTliEBr2OQfKSVnmgraBlmtSsrln1Bi+PSj6uLw//8GMBM/Q1ZHJfMcJRcxg7I9yqTDKrUJRv8unfIsGarNLDRj0MpbNw1V2sXc5MyiRLo8zU4KhmhAA7UdXncDKg4RhsS7ZaYy0wbcQ4Y6unNUOQuRThF3plBW5U9xhMKw4lQTCv7SQw64ZcEoOcnT4TRDiecsRZuu51w4m14B8GR8XEXDMtx3xOYIoe2zLigCzkaffhrbeIvJae6dgGSK1aBCklzuZqprrNbJ8tmALliUoUeXH/8Jpm2cTm8HB+m6tsjJqzpNfiwYf8=
  - secure: Ld36MRnTuSkLBBQNatAERjlIM03BGhNVjXfvp0MfqdYCYKKKsEv93EQ+XIIhJop9t05GUOptOOBe/PTkPM3J9ri/0fOOdnz11MNs6exT12rtPhHCX0LsMVxww+Yeyxh+m2rlanga7oqFopwi9nxTKx4bgPZOXmlISlNYLHgYRBrUFkzRgcX0P+nLZdqP3LJZye9eLemjtrtC53csCli7wiWafZTvNLhG135CioZRh/gw12qTfZ2abVvrZpj0qkk0SwVNa/uHQtUExYp06ciFg3B+hQvBuEoi+LnB2AGO2kRij68yEdTQtB5lEwNUt3h9h98Jmj+1Pfnpn+d38MWLDwwY9IdTL1ny6Jw0mMHRBGRnGTO27HcdJLR29AefKea9XcnYOeDTZiBfVxkgx3qx77LS7Tsr+KWZxejllihdp92AIcNGXhMcF4QfQ12UA63WwFwaAiC5R7IamCJ9+I8DimursUrbaQL5+KqbFCbL6RTGfM27mBufo3ExLVzPiRVmueM8iJpAHL1240ZXFj5Z9WFPHmAuzm0JsyT4qcNYOUpu5Ei88gA+jrin819GmE/xVXRmV/wV7kn1RvrBE8P6ODIx1sa62sQL2zwNUjZ2aShmYSk/MQFb9pUT/0ys2ngWoni8YIqXkB4it+9PunfgwRfSO4nVKYFIq183YRhibvg=
before_install:
- bash _scripts/install.sh
after_success:
- bash _scripts/deploy.sh
