version: "3"
services:
  test:
    build: .
    ports:
      - "3500:3500"
    container_name: gfw-mail-api-test
    environment:
      ALLOW_CONFIG_MUTATIONS: true
      NODE_ENV: test
      PORT: 3500
      QUEUE_NAME: mail_test
      QUEUE_URL: redis://redis
      SPARKPOST_API_KEY: foobar
    command: test
    depends_on:
      - redis

  redis:
    image: redis
    expose:
      - 6379
