apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mail
  name: mail
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: mail
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
      - name: mail
        image: vizzuality/mail
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "3500"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://mail.default.svc.cluster.local:3500
          - name: QUEUE_PROVIDER
            value: redis
          - name: QUEUE_NAME
            value: mail_staging
          - name: QUEUE_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: SPARKPOST_API_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: SPARKPOST_API_KEY
        ports:
          - containerPort: 3500
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3500
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3500
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15

      restartPolicy: Always
